"""FTS5 memory search service — full-text search over everything Threadline remembers.

WHY THIS MODULE EXISTS
----------------------
Agents and humans need a single entry-point to search across all kinds of
memory: ingested events, decisions, open loops, daily notes, and compiled
context fragments.  The ``memory_fts`` FTS5 virtual table (see ``db.py``)
stores them all; this module is the only place that queries it.

Keeping query construction in one module means:
- The sanitization strategy (agent-safe) is applied consistently everywhere.
- The FTS5 column contract (see ``services/fts.py``) is read in one place.
- MCP tools (Task 10) can import ``sanitize_query`` directly and apply the
  same rules before constructing queries.

QUERY SANITIZATION STRATEGY
----------------------------
FTS5 MATCH syntax includes operators (AND, OR, NOT, NEAR, ^, *, ", parens,
-) that raise ``OperationalError`` on malformed input.  Agent-supplied queries
must NEVER crash the server regardless of what the agent sends.

``sanitize_query(raw)`` deliberately treats all input as literal terms and
never as operators:
1. Extract every run of word characters with ``re.findall(r'\\w+', raw)``.
   This captures unicode word chars (\\w matches [a-zA-Z0-9_] plus unicode)
   and discards every FTS5 operator character in a single pass.
2. Wrap each token in double-quotes so FTS5 treats it as a phrase, not a
   keyword (e.g. ``"AND"`` is a literal term, not the AND operator).
3. Join with spaces — FTS5 implicit-AND semantics: all tokens must match.
4. If no tokens survive, return ``""`` — the caller must short-circuit and
   return ``[]`` without querying.

PUBLIC API
----------
``sanitize_query(raw: str) -> str``
    Convert a raw agent query string to a safe FTS5 MATCH expression.
    Returns ``""`` when there are no terms (caller must return [] without
    querying — see ``search_memory`` docstring).
    PUBLIC so MCP tools can reuse it.

``search_memory(db, query, project_key=None, limit=20) -> list[SearchHit]``
    Run a full-text search across ``memory_fts`` and return hits.
``SearchHit``
    Dataclass representing one search result (kind, ref_id, project_key,
    title, snippet).
``MAX_SEARCH_LIMIT``
    Hard upper bound on results returned.  Agents may request absurd limits;
    this constant prevents runaway result sets.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

# Explicit public surface — the MCP task (Task 10) imports exactly these.
__all__ = ["search_memory", "sanitize_query", "SearchHit", "MAX_SEARCH_LIMIT"]

# Maximum number of hits search_memory will ever return, regardless of the
# caller-supplied ``limit``.  Agents may request thousands of results; capping
# here prevents unbounded memory use and keeps FTS queries predictable.
MAX_SEARCH_LIMIT: int = 50

# FTS5 snippet window: number of tokens shown around each match.
_SNIPPET_TOKENS: int = 12

# Column index for the snippet call: 1 = body column (0-indexed).
# WHY 1 (body): the body field contains the full searchable text, so the
# snippet drawn from it is the most informative context for the caller.
# The title (index 0) is often truncated to FTS_TITLE_MAX chars, so a body
# snippet shows more surrounding context.
_SNIPPET_COL: int = 1


@dataclass
class SearchHit:
    """One search result from the ``memory_fts`` full-text index.

    Fields
    ------
    kind:
        Row type: one of ``"event"``, ``"decision"``, ``"open_loop"``,
        ``"daily_note"``, or ``"context_fragment"``.
    ref_id:
        Primary key of the underlying row in its native table (e.g. the
        ``decisions.id`` for a decision hit).
    project_key:
        Project the row belongs to.  Daily notes use ``""`` because they span
        all projects.
    title:
        Short label for display.  Truncated to ``FTS_TITLE_MAX`` characters at
        insert time (see ``services/fts.py``).
    snippet:
        Excerpt from the body field with matching tokens wrapped in
        ``[match]…[/match]`` markers.  Generated by FTS5 ``snippet()`` —
        up to ``_SNIPPET_TOKENS`` tokens around each match, with ``…``
        indicating omitted text.
    """

    kind: str
    ref_id: str
    project_key: str
    title: str
    snippet: str


def sanitize_query(raw: str) -> str:
    """Convert a raw agent query string into a safe FTS5 MATCH expression.

    WHY THIS EXISTS: FTS5 MATCH syntax contains operators (AND, OR, NOT, NEAR,
    ^, *, ", parens, -) that raise ``OperationalError`` on malformed input.
    An agent-supplied query must never crash the server — sanitization is the
    defensive layer between untrusted input and the FTS5 engine.

    STRATEGY: reduce path/filename queries to their meaningful stem so that
    searching ``app/api/routes/record_store.py`` finds events that only mention
    ``record_store``, then treat every token as a literal term (never operator).
    1. Path reduction: if ``raw`` contains ``/``, use the basename (last segment).
       Reason: path prefixes like ``app/``, ``api/``, ``routes/`` are required
       AND terms under the old approach, so a full-path query returns nothing
       unless every doc stored the full path — which event bodies rarely do.
    2. Extension strip: remove a trailing ``.word`` (1–6 alpha chars) so that
       ``record_store.py`` → ``record_store`` and ``DataTableHeader.tsx`` →
       ``DataTableHeader``.  Extensions add no search signal; as AND terms
       they silently drop docs that mention the identifier without the extension.
    3. Extract word-character runs: ``re.findall(r'\\w+', stem)`` captures
       alphanumeric + underscore + unicode word chars and discards every FTS5
       operator character in one pass.
    4. Wrap each token in double-quotes so FTS5 sees it as a phrase literal.
    5. Join with spaces — FTS5 implicit-AND: all quoted phrases must appear.
    6. Return ``""`` if no tokens survive — see ``search_memory`` for how
       this is handled (short-circuit to [] without querying).

    Parameters
    ----------
    raw:
        Arbitrary string from an agent or user.

    Returns
    -------
    str
        A FTS5-safe MATCH expression, or ``""`` if ``raw`` had no word chars.
    """
    stem = raw
    # Path → basename (last segment); path prefixes are rarely in event bodies
    if "/" in stem:
        stem = stem.rsplit("/", 1)[-1]
    # Strip file extension so .py / .tsx don't become required AND terms
    stem = re.sub(r"\.\w{1,6}$", "", stem)
    tokens = re.findall(r"\w+", stem)
    if not tokens:
        return ""
    return " ".join(f'"{token}"' for token in tokens)


async def search_memory(
    db: AsyncSession,
    query: str,
    project_key: str | None = None,
    limit: int = 20,
) -> list[SearchHit]:
    """Search the ``memory_fts`` FTS5 index and return ranked hits.

    WHAT it does:
    - Sanitizes ``query`` via ``sanitize_query`` to prevent FTS5 operator
      injection from crashing the server (agents may pass arbitrary strings).
    - Filters results by ``project_key`` when provided (UNINDEXED column;
      SQLite filters after FTS5 scoring).
    - Returns results ordered by FTS5 rank (bm25 descending relevance).
    - Clamps ``limit`` to the range [0, MAX_SEARCH_LIMIT] via
      ``min(max(0, limit), MAX_SEARCH_LIMIT)`` so agents cannot request
      arbitrarily large result sets.  ``limit <= 0`` returns ``[]`` without
      querying (a negative LIMIT in SQLite means "unlimited" — clamping to 0
      prevents that surprise).

    WHY short-circuit on empty sanitized query:
    An empty MATCH string would raise ``OperationalError`` in SQLite.  Rather
    than letting that bubble up, we return [] immediately when sanitization
    yields no tokens — there is nothing meaningful to search for.

    Parameters
    ----------
    db:
        Active async session.
    query:
        Raw search string.  Sanitized internally — callers pass it as-is.
    project_key:
        Optional filter.  When provided, only hits for this project are
        returned.  Pass ``None`` to search all projects.
    limit:
        Maximum hits to return.  Clamped to ``MAX_SEARCH_LIMIT`` (50);
        values <= 0 return ``[]``.

    Returns
    -------
    list[SearchHit]
        Hits in FTS5 rank order (best match first).  Empty list when the
        query has no searchable terms or no rows match.
    """
    safe_query = sanitize_query(query)
    if not safe_query:
        # sanitize_query found no word tokens — nothing to search.
        return []

    # Clamp limit on both ends: max(0, ...) guards against negative values
    # (SQLite treats LIMIT -1 as "unlimited"!), min(...) caps absurd requests.
    effective_limit = min(max(0, limit), MAX_SEARCH_LIMIT)
    if effective_limit == 0:
        # limit <= 0 means "no results wanted" — skip the query entirely.
        return []

    # FTS5 snippet() signature:
    #   snippet(table, col_index, match_start, match_end, ellipsis, num_tokens)
    # Column index 1 = body (see _SNIPPET_COL constant above).
    # Bound params only — the sanitized query string is still passed as a
    # bound parameter so SQLite handles escaping; we never interpolate it.
    snip_expr = (
        f"snippet(memory_fts, {_SNIPPET_COL},"
        f" '[match]', '[/match]', '…', {_SNIPPET_TOKENS}) AS snip"
    )
    select_clause = f"SELECT kind, ref_id, project_key, title, {snip_expr} FROM memory_fts"

    if project_key is not None:
        sql = text(
            f"{select_clause} "
            "WHERE memory_fts MATCH :q "
            "AND project_key = :pk "
            "ORDER BY rank LIMIT :limit"
        )
        rows = (
            await db.execute(
                sql, {"q": safe_query, "pk": project_key, "limit": effective_limit}
            )
        ).fetchall()
    else:
        sql = text(
            f"{select_clause} "
            "WHERE memory_fts MATCH :q "
            "ORDER BY rank LIMIT :limit"
        )
        rows = (
            await db.execute(sql, {"q": safe_query, "limit": effective_limit})
        ).fetchall()

    # Named access via row._mapping (keyed on SELECT-clause column aliases):
    # if the SELECT clause ever changes, a missing key raises KeyError loudly
    # instead of silently mis-mapping positional indexes onto the wrong fields.
    return [
        SearchHit(
            kind=row._mapping["kind"],
            ref_id=row._mapping["ref_id"],
            project_key=row._mapping["project_key"],
            title=row._mapping["title"],
            snippet=row._mapping["snip"],
        )
        for row in rows
    ]
