"""SQLAlchemy 2.0 declarative models for Threadline.

These tables are the source of truth for everything Threadline remembers.

Conventions that every column here follows:

- All primary keys are strings: either a human-chosen slug (``projects.key``)
  or a uuid4 hex string generated by ``utils/ids.py:new_id()``.
- All timestamp columns store ISO-8601 UTC strings produced by
  ``utils/time.py:iso_now()``. Never store naive or non-UTC values —
  timestamps are sorted as strings, so a single naive value breaks
  ``ORDER BY`` silently.
- Defaults are passed as callables (``default=iso_now``), not called values,
  so each row gets a fresh timestamp/id at insert time.
"""
from sqlalchemy import Boolean, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from threadline_core.utils.ids import new_id
from threadline_core.utils.time import iso_now


class Base(DeclarativeBase):
    """Shared declarative base; ``Base.metadata`` knows every table below."""


class Project(Base):
    """A long-running body of work (e.g. "acme-api") that agents report against.

    The ``key`` slug is chosen by humans and used as the foreign key everywhere else.
    """

    __tablename__ = "projects"

    key: Mapped[str] = mapped_column(String, primary_key=True)
    name: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    current_objective: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String, nullable=False, default="active")
    created_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)
    updated_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)


class AgentSession(Base):
    """One working stint by one agent on one project — opened when the agent
    starts, closed (with a summary) when it finishes.

    Provenance columns (all nullable for backward-compat with existing rows):
    - ``external_session_id``: the client's own session id (e.g. Claude Code's
      conversation UUID). Bridges the gap between the client's id namespace and
      Threadline's internal ``id`` primary key. The hook path writes this so
      ``session_ended`` events carrying the same external id can find and close
      the right session without ever knowing the Threadline primary key.
    - ``cwd``: working directory at session start, for human-readable context.
    - ``repo``: basename of the git root (best-effort, may be None).
    - ``branch``: git branch name at start (best-effort, may be None).
    - ``source``: how this session was opened — ``"hook"`` (via SessionStart
      hook) or ``"mcp"`` (via the MCP ``start_session`` tool).
    """

    __tablename__ = "agent_sessions"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=new_id)
    project_key: Mapped[str] = mapped_column(
        String, ForeignKey("projects.key"), nullable=False
    )
    agent_name: Mapped[str] = mapped_column(String, nullable=False)
    agent_type: Mapped[str] = mapped_column(String, nullable=False)
    started_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)
    ended_at: Mapped[str | None] = mapped_column(String, nullable=True)
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String, nullable=False, default="active")
    # Bridge column: the client's own session id (e.g. Claude Code conversation UUID).
    # Used to match incoming hook events to an existing Threadline AgentSession without
    # requiring the client to know Threadline's internal primary key.
    external_session_id: Mapped[str | None] = mapped_column(String, nullable=True)
    # Working directory at session start — human-readable context for dashboard.
    cwd: Mapped[str | None] = mapped_column(String, nullable=True)
    # Git repository basename at session start (best-effort; None if not in a repo).
    repo: Mapped[str | None] = mapped_column(String, nullable=True)
    # Git branch name at session start (best-effort; None if not in a repo).
    branch: Mapped[str | None] = mapped_column(String, nullable=True)
    # How this session was opened: "hook" (via SessionStart hook) or "mcp" (via MCP tool).
    source: Mapped[str | None] = mapped_column(String, nullable=True)


class AgentEvent(Base):
    """A single thing an agent reported happening (a commit, a decision, a
    blocker). This is the raw feed everything else is distilled from.
    """

    __tablename__ = "agent_events"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=new_id)
    session_id: Mapped[str | None] = mapped_column(
        String, ForeignKey("agent_sessions.id"), nullable=True
    )
    project_key: Mapped[str] = mapped_column(
        String, ForeignKey("projects.key"), nullable=False
    )
    event_type: Mapped[str] = mapped_column(String, nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    details_json: Mapped[str] = mapped_column(Text, nullable=False, default="{}")
    occurred_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)
    created_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)
    contains_secrets: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    allow_cloud_processing: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)


class DailyNote(Base):
    """The human-readable journal entry for one calendar day, summarizing what
    happened across all projects. One row per date.
    """

    __tablename__ = "daily_notes"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=new_id)
    date: Mapped[str] = mapped_column(String, nullable=False, unique=True)
    markdown: Mapped[str] = mapped_column(Text, nullable=False)
    html: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)
    updated_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)


class ProjectMemory(Base):
    """A durable fact about a project that agents should always know —
    its current state, its architecture, or a constraint to respect.
    """

    __tablename__ = "project_memories"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=new_id)
    project_key: Mapped[str] = mapped_column(
        String, ForeignKey("projects.key"), nullable=False
    )
    kind: Mapped[str] = mapped_column(String, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(String, nullable=False, default="active")
    created_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)
    updated_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)


class Decision(Base):
    """A choice that was made on a project and why. Decisions are never
    deleted — a newer one supersedes an older one via ``superseded_by``.
    """

    __tablename__ = "decisions"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=new_id)
    project_key: Mapped[str] = mapped_column(
        String, ForeignKey("projects.key"), nullable=False
    )
    statement: Mapped[str] = mapped_column(Text, nullable=False)
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    source_event_id: Mapped[str | None] = mapped_column(String, nullable=True)
    status: Mapped[str] = mapped_column(String, nullable=False, default="active")
    superseded_by: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)


class OpenLoop(Base):
    """An unfinished thread on a project — something started but not resolved,
    so the next agent (or human) knows to pick it up.
    """

    __tablename__ = "open_loops"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=new_id)
    project_key: Mapped[str] = mapped_column(
        String, ForeignKey("projects.key"), nullable=False
    )
    description: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(String, nullable=False, default="open")
    source_event_id: Mapped[str | None] = mapped_column(String, nullable=True)
    resolved_at: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)
    updated_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)


class ContinuationPrompt(Base):
    """A generated, ready-to-paste prompt that lets an agent resume work on a
    project. Stored so past prompts can be audited and reused.
    """

    __tablename__ = "continuation_prompts"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=new_id)
    project_key: Mapped[str] = mapped_column(
        String, ForeignKey("projects.key"), nullable=False
    )
    target_agent: Mapped[str] = mapped_column(String, nullable=False)
    budget_tokens: Mapped[int] = mapped_column(Integer, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    token_estimate: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)


class ContextFragment(Base):
    """A scored, reusable piece of context (in HTML/Markdown/JSON form) that
    can be assembled into agent context windows. Priority, freshness, and
    trust scores decide what gets included when space is tight.
    """

    __tablename__ = "context_fragments"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=new_id)
    project_key: Mapped[str] = mapped_column(
        String, ForeignKey("projects.key"), nullable=False
    )
    type: Mapped[str] = mapped_column(String, nullable=False)
    title: Mapped[str] = mapped_column(String, nullable=False)
    html: Mapped[str | None] = mapped_column(Text, nullable=True)
    markdown: Mapped[str | None] = mapped_column(Text, nullable=True)
    # DB column is named "json"; the Python attribute is json_data to avoid
    # shadowing the stdlib json module in this file's namespace.
    json_data: Mapped[str | None] = mapped_column("json", Text, nullable=True)
    priority: Mapped[int] = mapped_column(Integer, nullable=False, default=3)
    freshness_score: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    trust_score: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    status: Mapped[str] = mapped_column(String, nullable=False, default="active")
    superseded_by: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)
    updated_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)


class AuditLog(Base):
    """A permanent record of who (human or agent) did what to Threadline's
    own data — for accountability, not application logic.
    """

    __tablename__ = "audit_log"

    id: Mapped[str] = mapped_column(String, primary_key=True, default=new_id)
    actor: Mapped[str] = mapped_column(String, nullable=False)
    action: Mapped[str] = mapped_column(String, nullable=False)
    detail: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[str] = mapped_column(String, nullable=False, default=iso_now)
